preload = ~/.local/share/wallpapers/cyberpunk_2077_ultimate_edition_video_game_valerie-wallpaper-5120x1440.jpg
wallpaper = , ~/.local/share/wallpapers/cyberpunk_2077_ultimate_edition_video_game_valerie-wallpaper-5120x1440.jpg
